"""Forward-looking crisis scenario stress assumptions.

These are not forecasts or price targets. They are transparent analyst-defined
stress-test assumptions that convert a geopolitical scenario into expected
relative winners, losers, resources, and technology themes.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import pandas as pd


@dataclass(frozen=True)
class ScenarioExposure:
    scenario: str
    bucket: str
    ticker_or_theme: str
    name: str
    expected_direction: str
    impact_score: int
    confidence: str
    rationale: str
    key_risk_to_view: str
    time_horizon: str = "0-6 months"
    probability_weight: float = 0.25
    severity_score: int = 4
    inflation_impact: int = 0
    growth_impact: int = 0
    liquidity_impact: int = 0
    supply_chain_impact: int = 0
    policy_response: str = "Path-dependent policy response."
    trigger_definition: str = "Analyst-defined stress-test scenario."


SCENARIO_METADATA: dict[str, dict[str, float | int | str]] = {
    "China attacks Taiwan": {
        "time_horizon": "0-12 months",
        "probability_weight": 0.12,
        "severity_score": 5,
        "inflation_impact": 4,
        "growth_impact": -5,
        "liquidity_impact": -5,
        "supply_chain_impact": -5,
        "policy_response": "Emergency defense spending, export controls, sanctions, chip rationing, liquidity support.",
        "trigger_definition": "Direct military attack, blockade, or kinetic escalation around Taiwan.",
    },
    "China blockades Taiwan": {
        "time_horizon": "0-9 months",
        "probability_weight": 0.18,
        "severity_score": 4,
        "inflation_impact": 3,
        "growth_impact": -4,
        "liquidity_impact": -4,
        "supply_chain_impact": -5,
        "policy_response": "Shipping escorts, sanctions threats, chip allocation, strategic stockpile releases.",
        "trigger_definition": "Quarantine, blockade, major exercises, or coercive shipping disruption around Taiwan.",
    },
    "U.S. expands war in the Middle East": {
        "time_horizon": "0-6 months",
        "probability_weight": 0.22,
        "severity_score": 4,
        "inflation_impact": 5,
        "growth_impact": -3,
        "liquidity_impact": -3,
        "supply_chain_impact": -3,
        "policy_response": "Strategic petroleum reserve release, naval deployments, sanctions, emergency defense funding.",
        "trigger_definition": "Direct U.S. campaign expansion involving Iran-linked forces or regional state actors.",
    },
    "Strait of Hormuz closure": {
        "time_horizon": "0-3 months",
        "probability_weight": 0.10,
        "severity_score": 5,
        "inflation_impact": 5,
        "growth_impact": -4,
        "liquidity_impact": -4,
        "supply_chain_impact": -4,
        "policy_response": "Naval clearing operations, SPR release, energy rationing risk, emergency LNG/oil rerouting.",
        "trigger_definition": "Material interruption of tanker traffic through the Strait of Hormuz.",
    },
    "U.S. debt or Treasury liquidity scare": {
        "time_horizon": "0-6 months",
        "probability_weight": 0.18,
        "severity_score": 4,
        "inflation_impact": 1,
        "growth_impact": -4,
        "liquidity_impact": -5,
        "supply_chain_impact": -1,
        "policy_response": "Treasury buybacks, Fed liquidity facilities, fiscal negotiation, bill-market stabilization.",
        "trigger_definition": "Debt-ceiling stress, failed Treasury auction, or disorderly Treasury market functioning.",
    },
    "Regional bank and commercial real estate shock": {
        "time_horizon": "0-12 months",
        "probability_weight": 0.28,
        "severity_score": 3,
        "inflation_impact": -1,
        "growth_impact": -4,
        "liquidity_impact": -4,
        "supply_chain_impact": -1,
        "policy_response": "Deposit guarantees, bank funding programs, regulatory forbearance, possible rate cuts.",
        "trigger_definition": "Deposit flight, CRE credit losses, or failures among regional lenders.",
    },
    "Pandemic 2.0": {
        "time_horizon": "0-18 months",
        "probability_weight": 0.10,
        "severity_score": 4,
        "inflation_impact": 2,
        "growth_impact": -5,
        "liquidity_impact": -4,
        "supply_chain_impact": -4,
        "policy_response": "Public-health restrictions, fiscal stimulus, emergency monetary easing, vaccine funding.",
        "trigger_definition": "A materially more disruptive infectious disease outbreak with global market impact.",
    },
    "Inflation resurgence and second rate shock": {
        "time_horizon": "0-12 months",
        "probability_weight": 0.30,
        "severity_score": 3,
        "inflation_impact": 5,
        "growth_impact": -3,
        "liquidity_impact": -3,
        "supply_chain_impact": -1,
        "policy_response": "Higher-for-longer rates, reduced easing expectations, tighter financial conditions.",
        "trigger_definition": "Re-acceleration in inflation that forces central banks to tighten or delay cuts.",
    },
    "Cyberattack on U.S. financial infrastructure": {
        "time_horizon": "0-3 months",
        "probability_weight": 0.16,
        "severity_score": 4,
        "inflation_impact": 0,
        "growth_impact": -3,
        "liquidity_impact": -5,
        "supply_chain_impact": -2,
        "policy_response": "Market closures, emergency liquidity, cyber defense mobilization, payment-system support.",
        "trigger_definition": "Major attack on payments, exchanges, clearing, banks, or market data infrastructure.",
    },
    "AI mega-cap unwind": {
        "time_horizon": "0-12 months",
        "probability_weight": 0.26,
        "severity_score": 3,
        "inflation_impact": -1,
        "growth_impact": -3,
        "liquidity_impact": -3,
        "supply_chain_impact": 0,
        "policy_response": "Limited direct policy support unless credit or funding markets break.",
        "trigger_definition": "Valuation reset in AI, semiconductors, and mega-cap technology leadership.",
    },
}


SCENARIO_EXPOSURES: list[ScenarioExposure] = [
    ScenarioExposure(
        scenario="China attacks Taiwan",
        bucket="Resource",
        ticker_or_theme="GLD",
        name="Gold",
        expected_direction="Up",
        impact_score=4,
        confidence="Medium",
        rationale="Safe-haven demand usually rises when geopolitical tail risk, sanctions risk, and reserve diversification risk jump.",
        key_risk_to_view="A forced liquidity selloff can temporarily pull gold down with equities.",
    ),
    ScenarioExposure(
        scenario="China attacks Taiwan",
        bucket="Resource",
        ticker_or_theme="UUP",
        name="U.S. dollar",
        expected_direction="Up",
        impact_score=4,
        confidence="Medium",
        rationale="Global investors often seek dollar liquidity during severe cross-border shocks.",
        key_risk_to_view="If the crisis damages U.S. fiscal or military credibility, the dollar response could be weaker.",
    ),
    ScenarioExposure(
        scenario="China attacks Taiwan",
        bucket="Resource",
        ticker_or_theme="SHY",
        name="Short-term Treasuries",
        expected_direction="Up",
        impact_score=3,
        confidence="Medium",
        rationale="Cash-like government duration can benefit from de-risking without as much inflation duration risk as long bonds.",
        key_risk_to_view="A sanctions-driven inflation shock could keep yields high.",
    ),
    ScenarioExposure(
        scenario="China attacks Taiwan",
        bucket="Resource",
        ticker_or_theme="USO/XLE",
        name="Oil and energy security",
        expected_direction="Up",
        impact_score=2,
        confidence="Low-Medium",
        rationale="A Pacific war could disrupt shipping insurance, Asian demand, military fuel logistics, and broader commodity risk premia.",
        key_risk_to_view="A global recession shock could crush demand and offset supply-risk premia.",
    ),
    ScenarioExposure(
        scenario="China attacks Taiwan",
        bucket="Resource",
        ticker_or_theme="Rare earths",
        name="Rare earths and critical minerals",
        expected_direction="Up",
        impact_score=4,
        confidence="Medium",
        rationale="Defense electronics, magnets, batteries, drones, and precision systems depend on critical mineral supply chains.",
        key_risk_to_view="Public-equity access is imperfect, and many producers have country-specific political risk.",
    ),
    ScenarioExposure(
        scenario="China attacks Taiwan",
        bucket="Sector/ETF",
        ticker_or_theme="ITA/XAR",
        name="Aerospace and defense ETFs",
        expected_direction="Up",
        impact_score=5,
        confidence="Medium-High",
        rationale="A direct conflict would likely accelerate demand for missiles, air defense, naval systems, drones, satellites, and munitions.",
        key_risk_to_view="Defense stocks can sell off first in a broad liquidity crash before policy funding becomes visible.",
    ),
    ScenarioExposure(
        scenario="China attacks Taiwan",
        bucket="Sector/ETF",
        ticker_or_theme="CIBR/HACK",
        name="Cybersecurity ETFs",
        expected_direction="Up",
        impact_score=4,
        confidence="Medium",
        rationale="Cyberattacks against financial, cloud, telecom, logistics, and government systems would likely intensify.",
        key_risk_to_view="High valuation software can still fall if rates rise or investors dump growth assets.",
    ),
    ScenarioExposure(
        scenario="China attacks Taiwan",
        bucket="Sector/ETF",
        ticker_or_theme="SOXX/SMH",
        name="Semiconductor ETFs",
        expected_direction="Down then mixed",
        impact_score=-5,
        confidence="High",
        rationale="Taiwan is a major advanced chip manufacturing hub; supply interruption would pressure fabless chip designers and hardware chains.",
        key_risk_to_view="Longer term, non-Taiwan fab capacity, equipment, and reshoring beneficiaries could recover first.",
    ),
    ScenarioExposure(
        scenario="China attacks Taiwan",
        bucket="Sector/ETF",
        ticker_or_theme="XLK",
        name="Technology sector",
        expected_direction="Down",
        impact_score=-4,
        confidence="Medium-High",
        rationale="Mega-cap hardware, AI, smartphones, servers, and cloud capex are exposed to advanced semiconductor bottlenecks.",
        key_risk_to_view="Cash-rich software and cybersecurity firms may outperform the broader tech sector.",
    ),
    ScenarioExposure(
        scenario="China attacks Taiwan",
        bucket="Sector/ETF",
        ticker_or_theme="XLY",
        name="Consumer discretionary",
        expected_direction="Down",
        impact_score=-4,
        confidence="Medium",
        rationale="Consumer cyclicals face risk from wealth shocks, inflation, shipping disruption, and China revenue exposure.",
        key_risk_to_view="Fiscal stimulus or fast de-escalation could reduce the hit.",
    ),
    ScenarioExposure(
        scenario="China attacks Taiwan",
        bucket="Company",
        ticker_or_theme="LMT/NOC/GD/RTX",
        name="Defense primes",
        expected_direction="Up",
        impact_score=5,
        confidence="Medium-High",
        rationale="Missile defense, naval systems, aerospace, sensors, and munitions demand would likely rise.",
        key_risk_to_view="Budget timing and supply bottlenecks can delay earnings conversion.",
    ),
    ScenarioExposure(
        scenario="China attacks Taiwan",
        bucket="Company",
        ticker_or_theme="PANW/FTNT/CRWD",
        name="Cybersecurity leaders",
        expected_direction="Up",
        impact_score=4,
        confidence="Medium",
        rationale="Government and enterprise cyber hardening becomes urgent in a state-on-state conflict.",
        key_risk_to_view="Multiple compression can offset better fundamentals.",
    ),
    ScenarioExposure(
        scenario="China attacks Taiwan",
        bucket="Company",
        ticker_or_theme="TSM",
        name="Taiwan Semiconductor Manufacturing",
        expected_direction="Down",
        impact_score=-5,
        confidence="High",
        rationale="The direct geographic, operational, and political risk is extreme in this scenario.",
        key_risk_to_view="If the event is limited to a blockade scare and quickly resolves, the stock could rebound sharply.",
    ),
    ScenarioExposure(
        scenario="China attacks Taiwan",
        bucket="Company",
        ticker_or_theme="NVDA/AMD/AAPL",
        name="Advanced-chip-dependent leaders",
        expected_direction="Down",
        impact_score=-5,
        confidence="High",
        rationale="AI accelerators, CPUs/GPUs, iPhones, and other hardware depend heavily on advanced foundry capacity.",
        key_risk_to_view="Strategic stockpiles and alternative capacity could cushion the hit for some firms.",
    ),
    ScenarioExposure(
        scenario="China attacks Taiwan",
        bucket="Company",
        ticker_or_theme="INTC/GFS/AMAT/LRCX",
        name="Reshoring and fab-capacity beneficiaries",
        expected_direction="Mixed then up",
        impact_score=2,
        confidence="Low-Medium",
        rationale="A supply shock would increase political and customer urgency to diversify manufacturing outside Taiwan.",
        key_risk_to_view="Equipment makers also sell into Taiwan and China, so near-term order disruption could be severe.",
    ),
    ScenarioExposure(
        scenario="China attacks Taiwan",
        bucket="Technology",
        ticker_or_theme="Drones/ISR/satellites",
        name="Drones, intelligence, surveillance, and satellites",
        expected_direction="Up",
        impact_score=5,
        confidence="Medium-High",
        rationale="Pacific conflict would increase demand for distributed sensing, targeting, communications, and unmanned systems.",
        key_risk_to_view="Procurement bottlenecks and export controls can slow deployment.",
    ),
    ScenarioExposure(
        scenario="China attacks Taiwan",
        bucket="Technology",
        ticker_or_theme="Supply-chain AI",
        name="Supply-chain visibility and industrial automation",
        expected_direction="Up",
        impact_score=3,
        confidence="Medium",
        rationale="Companies would need better visibility into chips, components, logistics, and substitution options.",
        key_risk_to_view="Enterprise software budgets can freeze during recessionary shocks.",
    ),
    ScenarioExposure(
        scenario="China attacks Taiwan",
        bucket="Technology",
        ticker_or_theme="Cloud/AI buildout",
        name="Cloud and AI data-center buildout",
        expected_direction="Down then up",
        impact_score=-2,
        confidence="Medium",
        rationale="Advanced-chip shortages would delay AI server deployment, even if long-term AI demand remains intact.",
        key_risk_to_view="Existing inventory and premium pricing could protect some suppliers.",
    ),
    ScenarioExposure(
        scenario="U.S. expands war in the Middle East",
        bucket="Resource",
        ticker_or_theme="USO",
        name="Oil",
        expected_direction="Up",
        impact_score=5,
        confidence="High",
        rationale="Middle East escalation raises risk premia around crude, refined products, shipping insurance, and chokepoints.",
        key_risk_to_view="A demand shock or rapid OPEC spare-capacity response could cap gains.",
    ),
    ScenarioExposure(
        scenario="U.S. expands war in the Middle East",
        bucket="Resource",
        ticker_or_theme="XLE",
        name="Energy equities",
        expected_direction="Up",
        impact_score=4,
        confidence="Medium-High",
        rationale="Higher realized and expected energy prices usually support upstream cash flows.",
        key_risk_to_view="Windfall taxes, recession, or falling demand can weaken the equity response.",
    ),
    ScenarioExposure(
        scenario="U.S. expands war in the Middle East",
        bucket="Resource",
        ticker_or_theme="GLD",
        name="Gold",
        expected_direction="Up",
        impact_score=4,
        confidence="Medium",
        rationale="Gold tends to attract safe-haven flows when war risk and inflation risk rise together.",
        key_risk_to_view="Real-yield spikes can offset safe-haven demand.",
    ),
    ScenarioExposure(
        scenario="U.S. expands war in the Middle East",
        bucket="Resource",
        ticker_or_theme="UUP",
        name="U.S. dollar",
        expected_direction="Up",
        impact_score=3,
        confidence="Medium",
        rationale="Dollar liquidity often becomes more valuable when global funding and commodity trade stress rises.",
        key_risk_to_view="Large U.S. fiscal costs or weaker rate expectations could weigh on the dollar.",
    ),
    ScenarioExposure(
        scenario="U.S. expands war in the Middle East",
        bucket="Resource",
        ticker_or_theme="LNG/fertilizer",
        name="LNG, refined products, and fertilizer",
        expected_direction="Up",
        impact_score=4,
        confidence="Medium",
        rationale="Energy chokepoints can affect natural gas, diesel, petrochemicals, and fertilizer supply chains.",
        key_risk_to_view="Substitution routes and inventories can dampen the effect.",
    ),
    ScenarioExposure(
        scenario="U.S. expands war in the Middle East",
        bucket="Sector/ETF",
        ticker_or_theme="ITA/XAR",
        name="Aerospace and defense ETFs",
        expected_direction="Up",
        impact_score=5,
        confidence="High",
        rationale="Air defense, naval protection, munitions, surveillance, and logistics spending would likely increase.",
        key_risk_to_view="A short conflict may not materially change long-term orders.",
    ),
    ScenarioExposure(
        scenario="U.S. expands war in the Middle East",
        bucket="Sector/ETF",
        ticker_or_theme="JETS/travel",
        name="Airlines and travel",
        expected_direction="Down",
        impact_score=-5,
        confidence="High",
        rationale="Higher jet fuel, rerouted flights, weaker consumer confidence, and security risk pressure travel margins.",
        key_risk_to_view="Oil hedges and resilient demand can reduce the damage.",
    ),
    ScenarioExposure(
        scenario="U.S. expands war in the Middle East",
        bucket="Sector/ETF",
        ticker_or_theme="XLY",
        name="Consumer discretionary",
        expected_direction="Down",
        impact_score=-4,
        confidence="Medium",
        rationale="Energy inflation acts like a tax on consumers and can pressure discretionary spending.",
        key_risk_to_view="Strong labor markets or fiscal support can soften the hit.",
    ),
    ScenarioExposure(
        scenario="U.S. expands war in the Middle East",
        bucket="Sector/ETF",
        ticker_or_theme="TLT",
        name="Long-term Treasuries",
        expected_direction="Mixed",
        impact_score=-1,
        confidence="Low",
        rationale="Risk-off flows help duration, but oil-driven inflation and fiscal spending can push long yields higher.",
        key_risk_to_view="If recession risk dominates inflation risk, long Treasuries could rally strongly.",
    ),
    ScenarioExposure(
        scenario="U.S. expands war in the Middle East",
        bucket="Sector/ETF",
        ticker_or_theme="XLF",
        name="Financials",
        expected_direction="Down",
        impact_score=-3,
        confidence="Medium",
        rationale="Credit risk, slower growth, volatility, and funding stress can outweigh benefits from higher rates.",
        key_risk_to_view="Large banks can benefit from trading revenue and higher net interest income in some paths.",
    ),
    ScenarioExposure(
        scenario="U.S. expands war in the Middle East",
        bucket="Company",
        ticker_or_theme="XOM/CVX/COP/SLB",
        name="Energy producers and services",
        expected_direction="Up",
        impact_score=5,
        confidence="Medium-High",
        rationale="Higher oil and gas prices improve upstream economics and drilling-service demand.",
        key_risk_to_view="Political pressure and demand destruction can limit upside.",
    ),
    ScenarioExposure(
        scenario="U.S. expands war in the Middle East",
        bucket="Company",
        ticker_or_theme="LMT/NOC/GD/RTX",
        name="Defense primes",
        expected_direction="Up",
        impact_score=5,
        confidence="High",
        rationale="Missile defense, aircraft systems, naval systems, and munitions demand should rise.",
        key_risk_to_view="Order timing can lag stock-price reaction.",
    ),
    ScenarioExposure(
        scenario="U.S. expands war in the Middle East",
        bucket="Company",
        ticker_or_theme="PANW/FTNT/CRWD",
        name="Cybersecurity leaders",
        expected_direction="Up",
        impact_score=3,
        confidence="Medium",
        rationale="Regional war can spill into cyber operations against infrastructure, finance, and government systems.",
        key_risk_to_view="Software valuations can contract in a higher-rate inflation shock.",
    ),
    ScenarioExposure(
        scenario="U.S. expands war in the Middle East",
        bucket="Company",
        ticker_or_theme="Airlines/cruise",
        name="Fuel-sensitive travel companies",
        expected_direction="Down",
        impact_score=-5,
        confidence="High",
        rationale="Fuel costs, route disruption, insurance costs, and demand uncertainty pressure margins.",
        key_risk_to_view="Short-lived conflicts and hedging can produce fast rebounds.",
    ),
    ScenarioExposure(
        scenario="U.S. expands war in the Middle East",
        bucket="Company",
        ticker_or_theme="AMZN/retail",
        name="Logistics-heavy retailers",
        expected_direction="Down",
        impact_score=-2,
        confidence="Low-Medium",
        rationale="Fuel, freight, and consumer-stress costs can rise, pressuring margins.",
        key_risk_to_view="Scale players can gain share if smaller competitors are hurt more.",
    ),
    ScenarioExposure(
        scenario="U.S. expands war in the Middle East",
        bucket="Technology",
        ticker_or_theme="Missile defense",
        name="Missile defense, drones, and counter-drone systems",
        expected_direction="Up",
        impact_score=5,
        confidence="High",
        rationale="Air defense and unmanned systems are central to modern Middle East conflict escalation.",
        key_risk_to_view="Procurement capacity may become the bottleneck.",
    ),
    ScenarioExposure(
        scenario="U.S. expands war in the Middle East",
        bucket="Technology",
        ticker_or_theme="Energy security",
        name="Grid, LNG, refining, and energy infrastructure tech",
        expected_direction="Up",
        impact_score=4,
        confidence="Medium",
        rationale="Energy security, redundancy, storage, and monitoring become more valuable when oil and gas routes are threatened.",
        key_risk_to_view="Policy delays can slow investment.",
    ),
    ScenarioExposure(
        scenario="U.S. expands war in the Middle East",
        bucket="Technology",
        ticker_or_theme="Cyber defense",
        name="Cyber defense for infrastructure",
        expected_direction="Up",
        impact_score=4,
        confidence="Medium",
        rationale="Energy, ports, telecom, defense contractors, and banks become higher-priority cyber targets.",
        key_risk_to_view="Budget freezes can delay enterprise purchases.",
    ),
    ScenarioExposure(
        scenario="China blockades Taiwan",
        bucket="Resource",
        ticker_or_theme="GLD/UUP/SHY",
        name="Safe-haven basket",
        expected_direction="Up",
        impact_score=4,
        confidence="Medium",
        rationale="A blockade would likely push investors toward liquidity, dollar assets, and crisis hedges.",
        key_risk_to_view="A short coercive event could reverse quickly if shipping normalizes.",
    ),
    ScenarioExposure(
        scenario="China blockades Taiwan",
        bucket="Sector/ETF",
        ticker_or_theme="SOXX/SMH",
        name="Semiconductor ETFs",
        expected_direction="Down",
        impact_score=-4,
        confidence="High",
        rationale="Even without invasion, shipping disruption and inventory hoarding would pressure chip supply chains.",
        key_risk_to_view="Non-Taiwan capacity and firms with inventory could outperform.",
    ),
    ScenarioExposure(
        scenario="China blockades Taiwan",
        bucket="Company",
        ticker_or_theme="TSM/NVDA/AMD/AAPL",
        name="Taiwan and advanced-chip dependency",
        expected_direction="Down",
        impact_score=-5,
        confidence="High",
        rationale="A blockade directly threatens production, exports, and customer access to advanced chips.",
        key_risk_to_view="Markets could distinguish between direct Taiwan exposure and reshoring beneficiaries.",
    ),
    ScenarioExposure(
        scenario="China blockades Taiwan",
        bucket="Sector/ETF",
        ticker_or_theme="ITA/XAR",
        name="Defense and naval security",
        expected_direction="Up",
        impact_score=4,
        confidence="Medium-High",
        rationale="Naval deterrence, air defense, surveillance, and munitions demand would likely increase.",
        key_risk_to_view="If escalation remains below armed conflict, defense upside may be smaller than invasion risk implies.",
    ),
    ScenarioExposure(
        scenario="China blockades Taiwan",
        bucket="Technology",
        ticker_or_theme="Supply-chain AI",
        name="Supply-chain visibility and substitution software",
        expected_direction="Up",
        impact_score=3,
        confidence="Medium",
        rationale="Companies would urgently map chip inventory, supplier tiers, and alternate manufacturing routes.",
        key_risk_to_view="Software buying cycles can freeze if recession fears dominate.",
    ),
    ScenarioExposure(
        scenario="China blockades Taiwan",
        bucket="Sector/ETF",
        ticker_or_theme="XLY/industrials",
        name="Consumer and industrial cyclicals",
        expected_direction="Down",
        impact_score=-3,
        confidence="Medium",
        rationale="Electronics, autos, machinery, and discretionary goods rely on Asian shipping and chip availability.",
        key_risk_to_view="Fiscal stimulus or rapid de-escalation could soften downside.",
    ),
    ScenarioExposure(
        scenario="Strait of Hormuz closure",
        bucket="Resource",
        ticker_or_theme="USO/BNO",
        name="Crude oil",
        expected_direction="Up",
        impact_score=5,
        confidence="High",
        rationale="Hormuz is a critical oil chokepoint; interruption would create immediate supply and shipping premia.",
        key_risk_to_view="A fast reopening or coordinated spare-capacity response could reverse the spike.",
    ),
    ScenarioExposure(
        scenario="Strait of Hormuz closure",
        bucket="Resource",
        ticker_or_theme="UNG/LNG",
        name="Natural gas and LNG",
        expected_direction="Up",
        impact_score=4,
        confidence="Medium",
        rationale="Qatar-linked LNG and broader energy security fears would likely lift gas and LNG-linked assets.",
        key_risk_to_view="Regional gas market differences can make ETF exposure imprecise.",
    ),
    ScenarioExposure(
        scenario="Strait of Hormuz closure",
        bucket="Company",
        ticker_or_theme="XOM/CVX/COP/SLB",
        name="Energy producers and services",
        expected_direction="Up",
        impact_score=5,
        confidence="Medium-High",
        rationale="Higher crude and gas prices can lift upstream cash flows and service demand.",
        key_risk_to_view="Demand destruction and political intervention can cap equity upside.",
    ),
    ScenarioExposure(
        scenario="Strait of Hormuz closure",
        bucket="Sector/ETF",
        ticker_or_theme="JETS/XLY",
        name="Travel and consumer discretionary",
        expected_direction="Down",
        impact_score=-5,
        confidence="High",
        rationale="Fuel shock, weaker confidence, and inflation tax pressure travel and consumer cyclicals.",
        key_risk_to_view="Fuel hedges and short disruption windows can reduce damage.",
    ),
    ScenarioExposure(
        scenario="Strait of Hormuz closure",
        bucket="Resource",
        ticker_or_theme="GLD/UUP",
        name="Gold and dollar liquidity",
        expected_direction="Up",
        impact_score=4,
        confidence="Medium",
        rationale="War plus inflation plus funding stress tends to increase demand for liquidity and crisis hedges.",
        key_risk_to_view="Real-yield spikes can weigh on gold.",
    ),
    ScenarioExposure(
        scenario="Strait of Hormuz closure",
        bucket="Sector/ETF",
        ticker_or_theme="XLF/HYG/JNK",
        name="Financials and high-yield credit",
        expected_direction="Down",
        impact_score=-3,
        confidence="Medium",
        rationale="Energy inflation and recession risk can widen credit spreads and pressure bank risk appetite.",
        key_risk_to_view="Energy lenders may outperform if credit losses stay contained.",
    ),
    ScenarioExposure(
        scenario="U.S. debt or Treasury liquidity scare",
        bucket="Resource",
        ticker_or_theme="GLD",
        name="Gold",
        expected_direction="Up",
        impact_score=4,
        confidence="Medium",
        rationale="Confidence shocks in sovereign debt can increase demand for non-sovereign stores of value.",
        key_risk_to_view="Dollar liquidity scrambles can temporarily overwhelm gold demand.",
    ),
    ScenarioExposure(
        scenario="U.S. debt or Treasury liquidity scare",
        bucket="Resource",
        ticker_or_theme="UUP",
        name="U.S. dollar",
        expected_direction="Mixed",
        impact_score=-1,
        confidence="Low",
        rationale="Dollar liquidity demand conflicts with concern about U.S. fiscal governance.",
        key_risk_to_view="In a global risk-off event, the dollar can still rise despite U.S.-origin stress.",
    ),
    ScenarioExposure(
        scenario="U.S. debt or Treasury liquidity scare",
        bucket="Sector/ETF",
        ticker_or_theme="TLT/IEF",
        name="Intermediate and long Treasuries",
        expected_direction="Down then mixed",
        impact_score=-4,
        confidence="Medium",
        rationale="Treasury-market dysfunction would directly pressure duration and collateral confidence.",
        key_risk_to_view="Fed liquidity support could trigger a powerful reversal.",
    ),
    ScenarioExposure(
        scenario="U.S. debt or Treasury liquidity scare",
        bucket="Sector/ETF",
        ticker_or_theme="XLF/KRE",
        name="Banks and financials",
        expected_direction="Down",
        impact_score=-4,
        confidence="Medium-High",
        rationale="Banks rely on Treasuries as collateral and liquidity assets; market dysfunction raises funding risk.",
        key_risk_to_view="Policy backstops can reduce the tail risk quickly.",
    ),
    ScenarioExposure(
        scenario="U.S. debt or Treasury liquidity scare",
        bucket="Sector/ETF",
        ticker_or_theme="SHY/BIL",
        name="Bills and short-duration cash proxies",
        expected_direction="Mixed",
        impact_score=1,
        confidence="Low",
        rationale="Short-duration instruments have low rate risk but can be affected if the stress centers on bill payments.",
        key_risk_to_view="Specific bill maturities around a debt deadline may trade unusually.",
    ),
    ScenarioExposure(
        scenario="U.S. debt or Treasury liquidity scare",
        bucket="Sector/ETF",
        ticker_or_theme="SPY/QQQ",
        name="Broad equities",
        expected_direction="Down",
        impact_score=-4,
        confidence="Medium",
        rationale="Higher discount rates, funding stress, and weaker confidence pressure equity multiples.",
        key_risk_to_view="A quick deal can create a sharp relief rally.",
    ),
    ScenarioExposure(
        scenario="Regional bank and commercial real estate shock",
        bucket="Sector/ETF",
        ticker_or_theme="KRE",
        name="Regional banks",
        expected_direction="Down",
        impact_score=-5,
        confidence="High",
        rationale="Deposit flight, CRE losses, and funding stress directly hit regional-bank equity.",
        key_risk_to_view="Government guarantees or bank mergers can stabilize the group.",
    ),
    ScenarioExposure(
        scenario="Regional bank and commercial real estate shock",
        bucket="Sector/ETF",
        ticker_or_theme="VNQ/REITs",
        name="Real estate and REITs",
        expected_direction="Down",
        impact_score=-4,
        confidence="Medium-High",
        rationale="CRE credit stress, refinancing risk, and higher cap rates pressure real estate assets.",
        key_risk_to_view="Data centers, towers, and specialized REITs can diverge from office-heavy exposure.",
    ),
    ScenarioExposure(
        scenario="Regional bank and commercial real estate shock",
        bucket="Resource",
        ticker_or_theme="SHY/BIL",
        name="Cash-like short duration",
        expected_direction="Up",
        impact_score=4,
        confidence="Medium",
        rationale="Investors often move toward short-duration government liquidity during banking stress.",
        key_risk_to_view="If the stress becomes sovereign-credit stress, cash proxies need closer inspection.",
    ),
    ScenarioExposure(
        scenario="Regional bank and commercial real estate shock",
        bucket="Sector/ETF",
        ticker_or_theme="TLT",
        name="Long-term Treasuries",
        expected_direction="Up",
        impact_score=3,
        confidence="Medium",
        rationale="Recession and rate-cut expectations can support duration.",
        key_risk_to_view="Inflation persistence can block the bond rally.",
    ),
    ScenarioExposure(
        scenario="Regional bank and commercial real estate shock",
        bucket="Company",
        ticker_or_theme="JPM/MS/GS",
        name="Systemically important financials",
        expected_direction="Mixed",
        impact_score=1,
        confidence="Low-Medium",
        rationale="Large banks can gain deposits and acquisition opportunities but still face market-wide financial stress.",
        key_risk_to_view="Regulatory capital costs and contagion risk can outweigh share gains.",
    ),
    ScenarioExposure(
        scenario="Regional bank and commercial real estate shock",
        bucket="Sector/ETF",
        ticker_or_theme="XLP/XLV",
        name="Defensive equities",
        expected_direction="Relative up",
        impact_score=2,
        confidence="Medium",
        rationale="Staples and healthcare can outperform cyclical equities when credit tightens.",
        key_risk_to_view="They may still decline in absolute terms during broad de-risking.",
    ),
    ScenarioExposure(
        scenario="Pandemic 2.0",
        bucket="Company",
        ticker_or_theme="MRNA/PFE/JNJ/MRK",
        name="Vaccines, antivirals, and healthcare platforms",
        expected_direction="Up",
        impact_score=5,
        confidence="Medium",
        rationale="Testing, vaccines, antivirals, and healthcare capacity become strategically valuable.",
        key_risk_to_view="Variant biology, public adoption, and regulatory path can change winners.",
    ),
    ScenarioExposure(
        scenario="Pandemic 2.0",
        bucket="Sector/ETF",
        ticker_or_theme="XLV",
        name="Healthcare",
        expected_direction="Up",
        impact_score=3,
        confidence="Medium",
        rationale="Healthcare demand and defensive characteristics can support relative performance.",
        key_risk_to_view="Procedure delays can hurt some subsectors.",
    ),
    ScenarioExposure(
        scenario="Pandemic 2.0",
        bucket="Sector/ETF",
        ticker_or_theme="JETS/travel",
        name="Travel, leisure, and airlines",
        expected_direction="Down",
        impact_score=-5,
        confidence="High",
        rationale="Mobility restrictions and consumer caution directly hit travel demand.",
        key_risk_to_view="Milder disease severity could limit behavioral and policy response.",
    ),
    ScenarioExposure(
        scenario="Pandemic 2.0",
        bucket="Company",
        ticker_or_theme="AMZN/MSFT/GOOGL",
        name="Cloud, e-commerce, and digital infrastructure",
        expected_direction="Up",
        impact_score=3,
        confidence="Medium",
        rationale="Remote work, e-commerce, streaming, and cloud collaboration demand can rise.",
        key_risk_to_view="Valuation and advertising cyclicality can still pressure mega-cap tech.",
    ),
    ScenarioExposure(
        scenario="Pandemic 2.0",
        bucket="Resource",
        ticker_or_theme="USO/XLE",
        name="Oil and energy demand",
        expected_direction="Down",
        impact_score=-4,
        confidence="Medium-High",
        rationale="Mobility declines can sharply reduce transport fuel demand.",
        key_risk_to_view="Supply cuts can offset demand weakness.",
    ),
    ScenarioExposure(
        scenario="Pandemic 2.0",
        bucket="Sector/ETF",
        ticker_or_theme="XLP/WMT/COST",
        name="Staples and essential retail",
        expected_direction="Relative up",
        impact_score=3,
        confidence="Medium",
        rationale="Essential goods demand is more resilient and can benefit from stockpiling behavior.",
        key_risk_to_view="Supply shortages and labor costs can pressure margins.",
    ),
    ScenarioExposure(
        scenario="Inflation resurgence and second rate shock",
        bucket="Resource",
        ticker_or_theme="USO/XLE/DBA",
        name="Energy and commodity basket",
        expected_direction="Up",
        impact_score=4,
        confidence="Medium",
        rationale="Inflation resurgence is often tied to energy, food, or commodity pressure.",
        key_risk_to_view="Demand destruction can reverse commodity gains.",
    ),
    ScenarioExposure(
        scenario="Inflation resurgence and second rate shock",
        bucket="Sector/ETF",
        ticker_or_theme="TLT/VNQ",
        name="Long duration bonds and real estate",
        expected_direction="Down",
        impact_score=-5,
        confidence="High",
        rationale="Higher discount rates pressure duration-heavy bonds and rate-sensitive real estate.",
        key_risk_to_view="A sudden recession would likely reverse rates lower.",
    ),
    ScenarioExposure(
        scenario="Inflation resurgence and second rate shock",
        bucket="Sector/ETF",
        ticker_or_theme="XLK/QQQ",
        name="High-multiple growth technology",
        expected_direction="Down",
        impact_score=-4,
        confidence="Medium-High",
        rationale="Higher real rates compress long-duration equity multiples.",
        key_risk_to_view="AI earnings acceleration could offset multiple pressure for select names.",
    ),
    ScenarioExposure(
        scenario="Inflation resurgence and second rate shock",
        bucket="Resource",
        ticker_or_theme="UUP/SHY",
        name="Dollar and short-duration cash",
        expected_direction="Up",
        impact_score=3,
        confidence="Medium",
        rationale="Higher U.S. rates can support dollar and short-duration yield appeal.",
        key_risk_to_view="Fiscal stress or synchronized global tightening can complicate FX moves.",
    ),
    ScenarioExposure(
        scenario="Inflation resurgence and second rate shock",
        bucket="Sector/ETF",
        ticker_or_theme="XLP/XLV",
        name="Defensive pricing-power equities",
        expected_direction="Relative up",
        impact_score=2,
        confidence="Medium",
        rationale="Staples and healthcare can outperform more cyclical or rate-sensitive sectors.",
        key_risk_to_view="Margin pressure can still hurt if input costs rise faster than pricing.",
    ),
    ScenarioExposure(
        scenario="Inflation resurgence and second rate shock",
        bucket="Sector/ETF",
        ticker_or_theme="XLY",
        name="Consumer discretionary",
        expected_direction="Down",
        impact_score=-4,
        confidence="Medium",
        rationale="Higher rates and inflation pressure household purchasing power.",
        key_risk_to_view="Wage growth and fiscal support can cushion demand.",
    ),
    ScenarioExposure(
        scenario="Cyberattack on U.S. financial infrastructure",
        bucket="Sector/ETF",
        ticker_or_theme="CIBR/HACK",
        name="Cybersecurity ETFs",
        expected_direction="Up",
        impact_score=5,
        confidence="Medium-High",
        rationale="A systemic cyber event would likely pull forward spending on identity, endpoint, network, and cloud security.",
        key_risk_to_view="Broad tech selloffs can temporarily drag cyber stocks lower.",
    ),
    ScenarioExposure(
        scenario="Cyberattack on U.S. financial infrastructure",
        bucket="Company",
        ticker_or_theme="PANW/FTNT/CRWD",
        name="Cybersecurity leaders",
        expected_direction="Up",
        impact_score=5,
        confidence="Medium-High",
        rationale="Market infrastructure attacks make security budgets board-level emergency items.",
        key_risk_to_view="Attribution, customer exposure, or product blame could hurt individual firms.",
    ),
    ScenarioExposure(
        scenario="Cyberattack on U.S. financial infrastructure",
        bucket="Sector/ETF",
        ticker_or_theme="XLF/KRE",
        name="Banks and financials",
        expected_direction="Down",
        impact_score=-5,
        confidence="High",
        rationale="Payments and clearing disruption would directly impair financial-sector confidence.",
        key_risk_to_view="Fed and Treasury support can stabilize funding quickly.",
    ),
    ScenarioExposure(
        scenario="Cyberattack on U.S. financial infrastructure",
        bucket="Resource",
        ticker_or_theme="GLD/SHY/UUP",
        name="Safe-haven liquidity basket",
        expected_direction="Up",
        impact_score=4,
        confidence="Medium",
        rationale="A market-infrastructure shock should increase demand for liquid hedges and stores of value.",
        key_risk_to_view="If market plumbing is impaired, price discovery may be disorderly.",
    ),
    ScenarioExposure(
        scenario="Cyberattack on U.S. financial infrastructure",
        bucket="Technology",
        ticker_or_theme="Cloud resilience",
        name="Cloud resilience and backup infrastructure",
        expected_direction="Up",
        impact_score=4,
        confidence="Medium",
        rationale="Firms would invest in redundancy, disaster recovery, and zero-trust architecture.",
        key_risk_to_view="If a cloud provider is implicated, cloud names could be punished first.",
    ),
    ScenarioExposure(
        scenario="Cyberattack on U.S. financial infrastructure",
        bucket="Sector/ETF",
        ticker_or_theme="SPY/QQQ",
        name="Broad equities",
        expected_direction="Down",
        impact_score=-4,
        confidence="Medium",
        rationale="Market closures, confidence damage, and liquidity stress pressure risk assets.",
        key_risk_to_view="Rapid containment can create a fast relief rally.",
    ),
    ScenarioExposure(
        scenario="AI mega-cap unwind",
        bucket="Company",
        ticker_or_theme="NVDA/AMD/AVGO",
        name="AI semiconductor leaders",
        expected_direction="Down",
        impact_score=-5,
        confidence="Medium",
        rationale="Crowded positioning and high expectations make AI chip leaders vulnerable to capex or margin disappointment.",
        key_risk_to_view="Real earnings growth can keep outperformers resilient even through multiple compression.",
    ),
    ScenarioExposure(
        scenario="AI mega-cap unwind",
        bucket="Sector/ETF",
        ticker_or_theme="QQQ/XLK/SMH",
        name="Mega-cap tech and semiconductor ETFs",
        expected_direction="Down",
        impact_score=-5,
        confidence="Medium-High",
        rationale="Index concentration means AI leaders can drag broad growth benchmarks lower.",
        key_risk_to_view="Rotation into non-AI software or defensives can offset some index losses.",
    ),
    ScenarioExposure(
        scenario="AI mega-cap unwind",
        bucket="Sector/ETF",
        ticker_or_theme="XLP/XLV/SHY",
        name="Defensives and short-duration cash",
        expected_direction="Relative up",
        impact_score=3,
        confidence="Medium",
        rationale="A valuation unwind would likely favor lower-volatility, cash-flow-stable assets.",
        key_risk_to_view="Broad deleveraging can pressure nearly everything in absolute terms.",
    ),
    ScenarioExposure(
        scenario="AI mega-cap unwind",
        bucket="Company",
        ticker_or_theme="MSFT/GOOGL/AMZN",
        name="Cloud platform leaders",
        expected_direction="Mixed",
        impact_score=-2,
        confidence="Low-Medium",
        rationale="Cloud platforms may be punished for AI capex but retain durable enterprise cash flows.",
        key_risk_to_view="If AI monetization improves, they may recover faster than chip suppliers.",
    ),
    ScenarioExposure(
        scenario="AI mega-cap unwind",
        bucket="Sector/ETF",
        ticker_or_theme="XLE/XLF/XLI",
        name="Value and old-economy rotation",
        expected_direction="Relative up",
        impact_score=2,
        confidence="Low-Medium",
        rationale="Capital may rotate toward sectors with lower AI valuation exposure.",
        key_risk_to_view="If the unwind signals recession, cyclicals can fall too.",
    ),
    ScenarioExposure(
        scenario="AI mega-cap unwind",
        bucket="Technology",
        ticker_or_theme="AI efficiency",
        name="AI efficiency, inference optimization, and cost control",
        expected_direction="Up",
        impact_score=3,
        confidence="Medium",
        rationale="After a capex scare, investors and customers prioritize cheaper inference and measurable ROI.",
        key_risk_to_view="Public-market proxies are imperfect.",
    ),
]


def build_scenario_exposure_table() -> pd.DataFrame:
    """Return scenario stress assumptions as a dataframe."""

    exposures = pd.DataFrame([exposure.__dict__ for exposure in SCENARIO_EXPOSURES])
    return _apply_scenario_metadata(exposures)


def build_scenario_summary_table(exposures: pd.DataFrame) -> pd.DataFrame:
    """Summarize likely winners and losers for each scenario."""

    rows: list[dict[str, str]] = []
    for scenario, group in exposures.groupby("scenario", sort=False):
        winners = group[group["impact_score"] >= 3].sort_values(
            "impact_score", ascending=False
        )
        losers = group[group["impact_score"] <= -3].sort_values("impact_score")
        mixed = group[(group["impact_score"] > -3) & (group["impact_score"] < 3)]

        rows.append(
            {
                "scenario": scenario,
                "likely_growth": "; ".join(winners["name"].head(8)),
                "likely_pressure": "; ".join(losers["name"].head(8)),
                "mixed_or_path_dependent": "; ".join(mixed["name"].head(8)),
            }
        )
    return pd.DataFrame(rows)


def build_scenario_risk_matrix(exposures: pd.DataFrame) -> pd.DataFrame:
    """Summarize macro stress dimensions for each scenario."""

    dimension_cols = [
        "inflation_impact",
        "growth_impact",
        "liquidity_impact",
        "supply_chain_impact",
    ]
    first_cols = [
        "time_horizon",
        "probability_weight",
        "severity_score",
        "policy_response",
        "trigger_definition",
    ]
    rows: list[dict[str, float | int | str]] = []
    for scenario, group in exposures.groupby("scenario", sort=False):
        first = group.iloc[0]
        macro_abs = group[dimension_cols].iloc[0].abs().mean()
        scenario_risk_score = (
            float(first["probability_weight"])
            * float(first["severity_score"])
            * float(macro_abs)
        )
        row: dict[str, float | int | str] = {
            "scenario": scenario,
            **{column: first[column] for column in first_cols},
            **{column: first[column] for column in dimension_cols},
            "positive_exposures": int((group["impact_score"] > 0).sum()),
            "negative_exposures": int((group["impact_score"] < 0).sum()),
            "scenario_risk_score": scenario_risk_score,
        }
        rows.append(row)
    return pd.DataFrame(rows).sort_values("scenario_risk_score", ascending=False)


def build_scenario_bucket_summary(exposures: pd.DataFrame) -> pd.DataFrame:
    """Aggregate impact scores by scenario and exposure bucket."""

    grouped = (
        exposures.groupby(["scenario", "bucket"], sort=False)
        .agg(
            average_impact_score=("impact_score", "mean"),
            strongest_positive=("impact_score", "max"),
            strongest_negative=("impact_score", "min"),
            exposure_count=("impact_score", "size"),
        )
        .reset_index()
    )
    return grouped.sort_values(["scenario", "average_impact_score"], ascending=[True, False])


def export_scenario_tables(
    output_dir: str | Path,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Write scenario exposure and summary CSVs."""

    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    exposures = build_scenario_exposure_table()
    summary = build_scenario_summary_table(exposures)
    risk_matrix = build_scenario_risk_matrix(exposures)
    bucket_summary = build_scenario_bucket_summary(exposures)
    exposures.to_csv(output_path / "scenario_exposures.csv", index=False)
    summary.to_csv(output_path / "scenario_summary.csv", index=False)
    risk_matrix.to_csv(output_path / "scenario_risk_matrix.csv", index=False)
    bucket_summary.to_csv(output_path / "scenario_bucket_summary.csv", index=False)
    return exposures, summary, risk_matrix, bucket_summary


def _apply_scenario_metadata(exposures: pd.DataFrame) -> pd.DataFrame:
    """Overlay scenario-level macro assumptions onto each exposure row."""

    result = exposures.copy()
    for scenario, metadata in SCENARIO_METADATA.items():
        mask = result["scenario"] == scenario
        for column, value in metadata.items():
            result.loc[mask, column] = value

    result["risk_adjusted_impact_score"] = (
        result["impact_score"]
        * result["probability_weight"].astype(float)
        * result["severity_score"].astype(float)
    )
    result["absolute_risk_contribution"] = result["risk_adjusted_impact_score"].abs()
    return result
